Action()
{

	lr_start_transaction("02_delete_ticket");

	lr_start_transaction("Gotosite");
	
//	web_set_sockets_option("SSL_VERSION", "AUTO");

	web_add_auto_header("Sec-Fetch-Site", 
		"none");

	web_add_auto_header("Sec-Fetch-Dest", 
		"document");

	web_add_auto_header("Sec-Fetch-Mode", 
		"navigate");

	web_add_auto_header("Sec-Fetch-User", 
		"?1");

	web_add_auto_header("Upgrade-Insecure-Requests", 
		"1");

/*Correlation comment: Automatic rules - Do not change!  
Original value='129606.097367355zzzzzVDpzDDDDDDDDQQQQpziVi' 
Name ='userSession' 
Type ='Rule' 
AppName ='WebTours' 
RuleName ='AutoGeneratedRuleName_userSession_1'*/
/*	web_reg_save_param_attrib(
		"ParamName=userSession",
		"TagName=input",
		"Extract=value",
		"Name=userSession",
		"Type=hidden",
		SEARCH_FILTERS,
		"RequestUrl=nav.pl*",
		LAST);
		*/
	web_reg_save_param("userSession",
		"LB=name=\"userSession\" value=\"",
		"RB=\"/>",
		"NotFound=ERROR",
		LAST);

	web_reg_find("Fail=NotFound",
		"Text/DIG=A Session ID has been created and loaded into a cookie called MSO",
		LAST);
		
	web_url("WebTours", 
		"URL=http://localhost:1080/WebTours/", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=", 
		"Snapshot=t1.inf", 
		"Mode=HTML", 
		LAST);

	lr_end_transaction("Gotosite",LR_AUTO);

	lr_start_transaction("login");

	web_revert_auto_header("Sec-Fetch-User");

	web_add_auto_header("Sec-Fetch-Dest", 
		"frame");

	web_revert_auto_header("Upgrade-Insecure-Requests");

	web_add_header("Origin", 
		"http://localhost:1080");

	web_add_auto_header("Sec-Fetch-Site", 
		"same-origin");

	lr_think_time(40);
	
		web_reg_find("Fail=NotFound",
		"Text/DIG=User password was correct",
		LAST);
	
	web_reg_find("Text=Welcome, <b>{login}</b>",
		LAST);
	
	web_submit_data("login.pl",
		"Action=http://localhost:1080/cgi-bin/login.pl",
		"Method=POST",
		"TargetFrame=body",
		"RecContentType=text/html",
		"Referer=http://localhost:1080/cgi-bin/nav.pl?in=home",
		"Snapshot=t2.inf",
		"Mode=HTML",
		ITEMDATA,
		"Name=userSession", "Value={userSession}", ENDITEM,
		"Name=username", "Value={login}", ENDITEM,
		"Name=password", "Value={password}", ENDITEM,
		"Name=login.x", "Value=16", ENDITEM,
		"Name=login.y", "Value=2", ENDITEM,
		"Name=JSFormSubmit", "Value=off", ENDITEM,
		LAST);

	lr_end_transaction("login",LR_AUTO);

	lr_start_transaction("click_itinerary");

	web_add_auto_header("Sec-Fetch-User", 
		"?1");

	web_add_auto_header("Upgrade-Insecure-Requests", 
		"1");

	lr_think_time(33);
	
/*	web_reg_find("Fail=NotFound",
		"Text/DIG=User wants the intineraries.",
		LAST);
	web_reg_find("Fail=Found",
		"Text=No flights have been reserved.",
		LAST);
	   */
	   	web_reg_save_param("flight_id",
	                   "LB=name=\"flightID\" value=\"",
	                   "RB=\"",
	                   "Ord=ALL",
	                   LAST);
	
	web_reg_find("Fail=NotFound",
		"Text/DIG={firstName} {lastName}\n 's Flight Transaction Summary",
		LAST);	
	
	web_url("Itinerary Button", 
		"URL=http://localhost:1080/cgi-bin/welcome.pl?page=itinerary", 
		"TargetFrame=body", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://localhost:1080/cgi-bin/nav.pl?page=menu&in=home", 
		"Snapshot=t3.inf", 
		"Mode=HTML", 
		LAST);

	lr_end_transaction("click_itinerary",LR_AUTO);

	lr_start_transaction("delete_ticket");

	web_add_header("Origin", 
		"http://localhost:1080");

	lr_think_time(32);
	
/*	web_reg_find("Fail=NotFound",
		"Text/DIG=Flights List",
		LAST);

	web_reg_save_param("flight_id2",
	    "LB=name=\"flightID\" value=\"",
	    "RB=\"",
	    "Ord=ALL",
	    LAST);*/
	
if(atoi(lr_eval_string("{num}"))<atoi(lr_eval_string("{flight_id_count}"))){
if(atoi(lr_eval_string("{num}"))==1){


//if(atoi(lr_eval_string("{flight_id_count}"))>1){
	web_reg_find("Fail=NotFound",
		"Text/DIG=Flights List",
		LAST);
   	web_reg_save_param("flight_id2",
	    "LB=name=\"flightID\" value=\"",
	    "RB=\"",
	    "Ord=ALL",
	    LAST);

	 web_submit_form("web_submit_form",
	     ITEMDATA,
	    "Name=1","Value=on",ENDITEM,
	   // "Name=2","Value=on",ENDITEM,
	    "Name=removeFlights.x", "Value=66", ENDITEM, 
		"Name=removeFlights.y", "Value=6", ENDITEM,
		EXTRARES,
		"URL=http://localhost:1080/cgi-bin/itinerary.pl", 
		"Referer=http://localhost:1080/cgi-bin/itinerary.pl", ENDITEM,
		LAST);

	if((atoi(lr_eval_string("{flight_id2_count}"))-atoi(lr_eval_string("{flight_id_count}"))+1)>=atoi(lr_eval_string("{flight_id_count}"))){
		lr_error_message("Itinerary not deleted");
		}
	else
		{ lr_output_message("Itenerary deleted succuess");
		}
	

	}else if(atoi(lr_eval_string("{num}"))==2){ 
		
	web_reg_find("Fail=NotFound",
		"Text/DIG=Flights List",
		LAST);
web_reg_save_param("flight_id2",
	    "LB=name=\"flightID\" value=\"",
	    "RB=\"",
	    "Ord=ALL",
	    LAST);
		
		web_submit_form("web_submit_form",
	     ITEMDATA,
	    "Name=1","Value=on",ENDITEM,
	    "Name=2","Value=on",ENDITEM,
	    "Name=removeFlights.x", "Value=66", ENDITEM, 
		"Name=removeFlights.y", "Value=6", ENDITEM,
		EXTRARES,
		"URL=http://localhost:1080/cgi-bin/itinerary.pl", 
		"Referer=http://localhost:1080/cgi-bin/itinerary.pl", ENDITEM,
		LAST);


	if((atoi(lr_eval_string("{flight_id2_count}"))-atoi(lr_eval_string("{flight_id_count}"))+1)>=atoi(lr_eval_string("{flight_id_count}"))){
		lr_error_message("Itinerary not deleted");
		}
	else
		{ lr_output_message("Itenerary deleted succuess");
		}
	
	}else if(atoi(lr_eval_string("{num}"))==3){ 
		
	web_reg_find("Fail=NotFound",
		"Text/DIG=Flights List",
		LAST);
	web_reg_save_param("flight_id2",
	    "LB=name=\"flightID\" value=\"",
	    "RB=\"",
	    "Ord=ALL",
	    LAST);

		
		web_submit_form("web_submit_form",
	     ITEMDATA,
	    "Name=1","Value=on",ENDITEM,
	    "Name=2","Value=on",ENDITEM,
	    "Name=3","Value=on",ENDITEM,
	    "Name=removeFlights.x", "Value=66", ENDITEM, 
		"Name=removeFlights.y", "Value=6", ENDITEM,
		EXTRARES,
		"URL=http://localhost:1080/cgi-bin/itinerary.pl", 
		"Referer=http://localhost:1080/cgi-bin/itinerary.pl", ENDITEM,
		LAST);
		
	if((atoi(lr_eval_string("{flight_id2_count}"))-atoi(lr_eval_string("{flight_id_count}"))+1)>=atoi(lr_eval_string("{flight_id_count}"))){
		lr_error_message("Itinerary not deleted");
		}
	else
		{ lr_output_message("Itenerary deleted succuess");
		}
	}
}else if(atoi(lr_eval_string("{num}"))==atoi(lr_eval_string("{flight_id_count}"))){
      if(atoi(lr_eval_string("{num}"))==1){
            		
            	
	web_reg_find("Fail=NotFound",
		"Text/DIG=Flights List",
		LAST);

	 web_submit_form("web_submit_form",
	     ITEMDATA,
	    "Name=1","Value=on",ENDITEM,
	    "Name=removeFlights.x", "Value=66", ENDITEM, 
		"Name=removeFlights.y", "Value=6", ENDITEM,
		EXTRARES,
		"URL=http://localhost:1080/cgi-bin/itinerary.pl", 
		"Referer=http://localhost:1080/cgi-bin/itinerary.pl", ENDITEM,
		LAST);
	 	web_reg_find("Fail=NotFound",
		"Text/DIG=No flights have been reserved",
		LAST);
            		
	}else if(atoi(lr_eval_string("{num}"))==2){ 
		
	web_reg_find("Fail=NotFound",
		"Text/DIG=Flights List",
		LAST);

		web_submit_form("web_submit_form",
	     ITEMDATA,
	    "Name=1","Value=on",ENDITEM,
	    "Name=2","Value=on",ENDITEM,
	    "Name=removeFlights.x", "Value=66", ENDITEM, 
		"Name=removeFlights.y", "Value=6", ENDITEM,
		EXTRARES,
		"URL=http://localhost:1080/cgi-bin/itinerary.pl", 
		"Referer=http://localhost:1080/cgi-bin/itinerary.pl", ENDITEM,
		LAST);


	 	web_reg_find("Fail=NotFound",
		"Text/DIG=No flights have been reserved",
		LAST);
           
	
	}else if(atoi(lr_eval_string("{num}"))==3){ 
		
	web_reg_find("Fail=NotFound",
		"Text/DIG=Flights List",
		LAST);
		
		web_submit_form("web_submit_form",
	     ITEMDATA,
	    "Name=1","Value=on",ENDITEM,
	    "Name=2","Value=on",ENDITEM,
	    "Name=3","Value=on",ENDITEM,
	    "Name=removeFlights.x", "Value=66", ENDITEM, 
		"Name=removeFlights.y", "Value=6", ENDITEM,
		EXTRARES,
		"URL=http://localhost:1080/cgi-bin/itinerary.pl", 
		"Referer=http://localhost:1080/cgi-bin/itinerary.pl", ENDITEM,
		LAST);
						
	 web_reg_find("Fail=NotFound",
		"Text/DIG=No flights have been reserved",
		LAST);
         }
            } else if (atoi(lr_eval_string("{num}"))>atoi(lr_eval_string("{flight_id_count}"))){
	lr_error_message("not tickets");

            }

	lr_end_transaction("delete_ticket",LR_AUTO);

	lr_start_transaction("logout");

	web_revert_auto_header("Sec-Fetch-User");

	web_add_header("Sec-Fetch-User", 
		"?1");

	lr_think_time(24);
	
	web_reg_find("Fail=NotFound",
		"Text/DIG=A Session ID has been created and loaded into a cookie called MSO",
		LAST);
	
	web_url("SignOff Button", 
		"URL=http://localhost:1080/cgi-bin/welcome.pl?signOff=1", 
		"TargetFrame=body", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://localhost:1080/cgi-bin/nav.pl?page=menu&in=itinerary", 
		"Snapshot=t5.inf", 
		"Mode=HTML", 
		LAST);

	lr_end_transaction("logout",LR_AUTO);

	lr_end_transaction("02_delete_ticket",LR_AUTO);

	return 0;
}